name: frontend
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.5.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  font_awesome_flutter: ^10.8.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  flutter_image_compress: ^2.3.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
